import blogImages from "./BlogsImages";
const BlogsData = [
  {
    id: 1,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Seafood", "Cooking", "Tips", "Photography"],
    title: "Cajun Seafood Pasta",
    text: "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of…",
    hashTags: ["Cooking", "Seafood"],
    detailText:
      "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation. Bay scallops are preferred, but the larger sea scallops can be used if they are cut in half. This dish can also be placed in a casserole dish and placed under the broiler until the top turns golden brown",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",    
    ],
    images:[
        blogImages.blog01,
        blogImages.blogDetail01,
        blogImages.blogDetail11,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "1 pound dry fettuccine pasta",
      "2 cups heavy whipping cream",
      "1 cup chopped green onions",
      "1 cup chopped parsley",
      "1 tablespoon chopped fresh basil",
      "1 tablespoon chopped fresh thyme",
      "2 teaspoons salt",
      "2 teaspoons ground black pepper",
      "1 ½ teaspoons crushed red pepper flakes",
      "1 teaspoon ground white pepper",
      "½ pound shrimp, peeled and deveined",
      "½ pound scallops",
      "½ cup shredded Swiss cheese",
      "½ cup grated Parmesan cheese",
    ],
    Directions: [
      "Fill a large pot with lightly salted water and bring to a rolling boil. Cook fettuccine at a boil until tender yet firm to the bite, about 8 minutes. Drain once done cooking.",
      "Meanwhile, pour cream into a large skillet. Cook over medium heat, stirring constantly, until just about boiling. Reduce heat and add green onions, parsley, basil, thyme, salt, black pepper, red pepper flakes, and white pepper. Simmer until thickened, 7 to 8 minutes.",
      "Stir in shrimp and scallops. Cook until shrimp is no longer translucent. Stir in cheeses, blending well.",
    ],
  },
  {
    id: 2,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Grille", "Cooking", "Tips", "Photography"],
    title: "Scott Hibb's Amazing Whisky Grilled Baby Back Ribs",
    text: "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve!…",
    hashTags: ["Cooking", "Grille"],
    detailText:
      "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! I have found that the major restaurant chains who make this awesome dish pre-cook their ribs SLOWLY before the quick grilling process.",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog02,
        blogImages.blogDetail02,
        blogImages.blogDetail12,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "2 (2 pound) slabs baby back pork ribs",
      "coarsely ground black pepper",
      "1 tablespoon ground red chile pepper ",
      "2 ¼ tablespoons vegetable oil",
      "½ cup minced onion ",
      "1 ½ cups water",
      "½ cup tomato paste",
      "½ cup white vinegar",
      "½ cup brown sugar",
      "2 ½ tablespoons honey",
      "2 tablespoons Worcestershire sauce",
      "2 teaspoons salt",
      "¼ teaspoon coarsely ground black pepper",
      "1 ¼ teaspoons liquid smoke flavoring",
      "2 teaspoons whiskey",
      "2 teaspoons garlic powder ",
      "¼ teaspoon paprika ",
      "½ teaspoon onion powder",
      "1 tablespoon dark molasses",
      "½ tablespoon ground red chile pepper",
    ],
    Directions: [
      "Preheat oven to 300 degree F (150 degrees C).",
      "Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.",
      "Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper. Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside",
      "Preheat an outdoor grill for high heat",
      "Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they're grilling, just before you serve them (adding it too early will burn it).",
    ],
  },
  {
    id: 3,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Seafood", "Cooking", "Tips", "Photography"],
    title: "Cajun Seafood Pasta",
    text: "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation…",
    hashTags: ["Cooking", "Seafood"],
    detailText:
      "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation. Bay scallops are preferred, but the larger sea scallops can be used if they are cut in half. This dish can also be placed in a casserole dish and placed under the broiler until the top turns golden brown",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog03,
        blogImages.blogDetail03,
        blogImages.blogDetail13,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "1 pound dry fettuccine pasta",
      "2 cups heavy whipping cream",
      "1 cup chopped green onions",
      "1 cup chopped parsley",
      "1 tablespoon chopped fresh basil",
      "1 tablespoon chopped fresh thyme",
      "2 teaspoons salt",
      "2 teaspoons ground black pepper",
      "1 ½ teaspoons crushed red pepper flakes",
      "1 teaspoon ground white pepper",
      "½ pound shrimp, peeled and deveined",
      "½ pound scallops",
      "½ cup shredded Swiss cheese",
      "½ cup grated Parmesan cheese",
    ],
    Directions: [
      "Fill a large pot with lightly salted water and bring to a rolling boil. Cook fettuccine at a boil until tender yet firm to the bite, about 8 minutes. Drain once done cooking.",
      "Meanwhile, pour cream into a large skillet. Cook over medium heat, stirring constantly, until just about boiling. Reduce heat and add green onions, parsley, basil, thyme, salt, black pepper, red pepper flakes, and white pepper. Simmer until thickened, 7 to 8 minutes.",
      "Stir in shrimp and scallops. Cook until shrimp is no longer translucent. Stir in cheeses, blending well.",
    ],
  },
  {
    id: 4,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Grille", "Cooking", "Tips", "Photography"],
    title: "Scott Hibb's Amazing Whisky Grilled Baby Back Ribs",
    text: "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve!…",
    hashTags: ["Cooking", "Grille"],
    detailText:
      "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! I have found that the major restaurant chains who make this awesome dish pre-cook their ribs SLOWLY before the quick grilling process.",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog04,
        blogImages.blogDetail04,
        blogImages.blogDetail14,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "2 (2 pound) slabs baby back pork ribs",
      "coarsely ground black pepper",
      "1 tablespoon ground red chile pepper ",
      "2 ¼ tablespoons vegetable oil",
      "½ cup minced onion ",
      "1 ½ cups water",
      "½ cup tomato paste",
      "½ cup white vinegar",
      "½ cup brown sugar",
      "2 ½ tablespoons honey",
      "2 tablespoons Worcestershire sauce",
      "2 teaspoons salt",
      "¼ teaspoon coarsely ground black pepper",
      "1 ¼ teaspoons liquid smoke flavoring",
      "2 teaspoons whiskey",
      "2 teaspoons garlic powder ",
      "¼ teaspoon paprika ",
      "½ teaspoon onion powder",
      "1 tablespoon dark molasses",
      "½ tablespoon ground red chile pepper",
    ],
    Directions: [
      "Preheat oven to 300 degree F (150 degrees C).",
      "Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.",
      "Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper. Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside",
      "Preheat an outdoor grill for high heat",
      "Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they're grilling, just before you serve them (adding it too early will burn it).",
    ],
  },
  {
    id: 5,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Seafood", "Cooking", "Tips", "Photography"],
    title: "Cajun Seafood Pasta",
    text: "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation…",
    hashTags: ["Cooking", "Seafood"],
    detailText:
      "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation. Bay scallops are preferred, but the larger sea scallops can be used if they are cut in half. This dish can also be placed in a casserole dish and placed under the broiler until the top turns golden brown",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog05,
        blogImages.blogDetail05,
        blogImages.blogDetail15,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "1 pound dry fettuccine pasta",
      "2 cups heavy whipping cream",
      "1 cup chopped green onions",
      "1 cup chopped parsley",
      "1 tablespoon chopped fresh basil",
      "1 tablespoon chopped fresh thyme",
      "2 teaspoons salt",
      "2 teaspoons ground black pepper",
      "1 ½ teaspoons crushed red pepper flakes",
      "1 teaspoon ground white pepper",
      "½ pound shrimp, peeled and deveined",
      "½ pound scallops",
      "½ cup shredded Swiss cheese",
      "½ cup grated Parmesan cheese",
    ],
    Directions: [
      "Fill a large pot with lightly salted water and bring to a rolling boil. Cook fettuccine at a boil until tender yet firm to the bite, about 8 minutes. Drain once done cooking.",
      "Meanwhile, pour cream into a large skillet. Cook over medium heat, stirring constantly, until just about boiling. Reduce heat and add green onions, parsley, basil, thyme, salt, black pepper, red pepper flakes, and white pepper. Simmer until thickened, 7 to 8 minutes.",
      "Stir in shrimp and scallops. Cook until shrimp is no longer translucent. Stir in cheeses, blending well.",
    ],
  },
  {
    id: 6,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Grille", "Cooking", "Tips", "Photography"],
    title: "Scott Hibb's Amazing Whisky Grilled Baby Back Ribs",
    text: "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve!…",
    hashTags: ["Cooking", "Grille"],
    detailText:
      "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! I have found that the major restaurant chains who make this awesome dish pre-cook their ribs SLOWLY before the quick grilling process.",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog06,
        blogImages.blogDetail06,
        blogImages.blogDetail16,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "2 (2 pound) slabs baby back pork ribs",
      "coarsely ground black pepper",
      "1 tablespoon ground red chile pepper ",
      "2 ¼ tablespoons vegetable oil",
      "½ cup minced onion ",
      "1 ½ cups water",
      "½ cup tomato paste",
      "½ cup white vinegar",
      "½ cup brown sugar",
      "2 ½ tablespoons honey",
      "2 tablespoons Worcestershire sauce",
      "2 teaspoons salt",
      "¼ teaspoon coarsely ground black pepper",
      "1 ¼ teaspoons liquid smoke flavoring",
      "2 teaspoons whiskey",
      "2 teaspoons garlic powder ",
      "¼ teaspoon paprika ",
      "½ teaspoon onion powder",
      "1 tablespoon dark molasses",
      "½ tablespoon ground red chile pepper",
    ],
    Directions: [
      "Preheat oven to 300 degree F (150 degrees C).",
      "Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.",
      "Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper. Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside",
      "Preheat an outdoor grill for high heat",
      "Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they're grilling, just before you serve them (adding it too early will burn it).",
    ],
  },
  {
    id: 7,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Seafood", "Cooking", "Tips", "Photography"],
    title: "Cajun Seafood Pasta",
    text: "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation…",
    hashTags: ["Cooking", "Seafood"],
    detailText:
      "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation. Bay scallops are preferred, but the larger sea scallops can be used if they are cut in half. This dish can also be placed in a casserole dish and placed under the broiler until the top turns golden brown",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog07,
        blogImages.blogDetail07,
        blogImages.blogDetail17,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "1 pound dry fettuccine pasta",
      "2 cups heavy whipping cream",
      "1 cup chopped green onions",
      "1 cup chopped parsley",
      "1 tablespoon chopped fresh basil",
      "1 tablespoon chopped fresh thyme",
      "2 teaspoons salt",
      "2 teaspoons ground black pepper",
      "1 ½ teaspoons crushed red pepper flakes",
      "1 teaspoon ground white pepper",
      "½ pound shrimp, peeled and deveined",
      "½ pound scallops",
      "½ cup shredded Swiss cheese",
      "½ cup grated Parmesan cheese",
    ],
    Directions: [
      "Fill a large pot with lightly salted water and bring to a rolling boil. Cook fettuccine at a boil until tender yet firm to the bite, about 8 minutes. Drain once done cooking.",
      "Meanwhile, pour cream into a large skillet. Cook over medium heat, stirring constantly, until just about boiling. Reduce heat and add green onions, parsley, basil, thyme, salt, black pepper, red pepper flakes, and white pepper. Simmer until thickened, 7 to 8 minutes.",
      "Stir in shrimp and scallops. Cook until shrimp is no longer translucent. Stir in cheeses, blending well.",
    ],
  },
  {
    id: 8,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Grille", "Cooking", "Tips", "Photography"],
    title: "Scott Hibb's Amazing Whisky Grilled Baby Back Ribs",
    text: "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve!…",
    hashTags: ["Cooking", "Grille"],
    detailText:
      "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! I have found that the major restaurant chains who make this awesome dish pre-cook their ribs SLOWLY before the quick grilling process.",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog08,
        blogImages.blogDetail08,
        blogImages.blogDetail18,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "2 (2 pound) slabs baby back pork ribs",
      "coarsely ground black pepper",
      "1 tablespoon ground red chile pepper ",
      "2 ¼ tablespoons vegetable oil",
      "½ cup minced onion ",
      "1 ½ cups water",
      "½ cup tomato paste",
      "½ cup white vinegar",
      "½ cup brown sugar",
      "2 ½ tablespoons honey",
      "2 tablespoons Worcestershire sauce",
      "2 teaspoons salt",
      "¼ teaspoon coarsely ground black pepper",
      "1 ¼ teaspoons liquid smoke flavoring",
      "2 teaspoons whiskey",
      "2 teaspoons garlic powder ",
      "¼ teaspoon paprika ",
      "½ teaspoon onion powder",
      "1 tablespoon dark molasses",
      "½ tablespoon ground red chile pepper",
    ],
    Directions: [
      "Preheat oven to 300 degree F (150 degrees C).",
      "Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.",
      "Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper. Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside",
      "Preheat an outdoor grill for high heat",
      "Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they're grilling, just before you serve them (adding it too early will burn it).",
    ],
  },
  {
    id: 9,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Seafood", "Cooking", "Tips", "Photography"],
    title: "Cajun Seafood Pasta",
    text: "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation…",
    hashTags: ["Cooking", "Seafood"],
    detailText:
      "This Cajun-inspired seafood pasta recipe is a hot one, but delicious! If you don't like as much spice, divide the amounts of pepper in half. Better to add more later than spoil your creation. Bay scallops are preferred, but the larger sea scallops can be used if they are cut in half. This dish can also be placed in a casserole dish and placed under the broiler until the top turns golden brown",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog09,
        blogImages.blogDetail09,
        blogImages.blogDetail19,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "1 pound dry fettuccine pasta",
      "2 cups heavy whipping cream",
      "1 cup chopped green onions",
      "1 cup chopped parsley",
      "1 tablespoon chopped fresh basil",
      "1 tablespoon chopped fresh thyme",
      "2 teaspoons salt",
      "2 teaspoons ground black pepper",
      "1 ½ teaspoons crushed red pepper flakes",
      "1 teaspoon ground white pepper",
      "½ pound shrimp, peeled and deveined",
      "½ pound scallops",
      "½ cup shredded Swiss cheese",
      "½ cup grated Parmesan cheese",
    ],
    Directions: [
      "Fill a large pot with lightly salted water and bring to a rolling boil. Cook fettuccine at a boil until tender yet firm to the bite, about 8 minutes. Drain once done cooking.",
      "Meanwhile, pour cream into a large skillet. Cook over medium heat, stirring constantly, until just about boiling. Reduce heat and add green onions, parsley, basil, thyme, salt, black pepper, red pepper flakes, and white pepper. Simmer until thickened, 7 to 8 minutes.",
      "Stir in shrimp and scallops. Cook until shrimp is no longer translucent. Stir in cheeses, blending well.",
    ],
  },
  {
    id: 10,
    by: "Annalisa L",
    in: "December 29, 2021",
    tags: ["Grille", "Cooking", "Tips", "Photography"],
    title: "Scott Hibb's Amazing Whisky Grilled Baby Back Ribs",
    text: "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve!…",
    hashTags: ["Cooking", "Grille"],
    detailText:
      "Man, when your guests bite into these at the Memorial Day cookout, they'll savor meat so tender and juicy that it slides right off the bone and gets you the respect you deserve! I have found that the major restaurant chains who make this awesome dish pre-cook their ribs SLOWLY before the quick grilling process.",
    detailQuote: "There Is No Love Sincerer Than The Love Of Food.",
    detailTitle01: "How To Prepare Your Grill",
    detailMainDesc:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.",
    detailDesc: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Tincidunt pharetra ut lobortis id.",
      "Commodo sit libero lacus a egestas penatibus pretium quis lorem.",
    ],
    images:[
        blogImages.blog10,
        blogImages.blogDetail10,
        blogImages.blogDetail20,
    ],
    videoDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt pharetra ut lobortis id. Commodo sit libero lacus a egestas penatibus pretium quis lorem. Purus morbi sagittis, faucibus odio. Elementum felis nibh at purus consectetur phasellus lacus, pellentesque dictumst."
    ,detailIngrediientsTitle: "",
    ingredients: [
      "2 (2 pound) slabs baby back pork ribs",
      "coarsely ground black pepper",
      "1 tablespoon ground red chile pepper ",
      "2 ¼ tablespoons vegetable oil",
      "½ cup minced onion ",
      "1 ½ cups water",
      "½ cup tomato paste",
      "½ cup white vinegar",
      "½ cup brown sugar",
      "2 ½ tablespoons honey",
      "2 tablespoons Worcestershire sauce",
      "2 teaspoons salt",
      "¼ teaspoon coarsely ground black pepper",
      "1 ¼ teaspoons liquid smoke flavoring",
      "2 teaspoons whiskey",
      "2 teaspoons garlic powder ",
      "¼ teaspoon paprika ",
      "½ teaspoon onion powder",
      "1 tablespoon dark molasses",
      "½ tablespoon ground red chile pepper",
    ],
    Directions: [
      "Preheat oven to 300 degree F (150 degrees C).",
      "Cut each full rack of ribs in half, so that you have 4 half racks. Sprinkle salt and pepper (more pepper than salt), and 1 tablespoon chile pepper over meat. Wrap each half rack in aluminum foil. Bake for 2 1/2 hours.",
      "Meanwhile, heat oil in a medium saucepan over medium heat. Cook and stir the onions in oil for 5 minutes. Stir in water, tomato paste, vinegar, brown sugar, honey, and Worcestershire sauce. Season with 2 teaspoons salt, 1/4 teaspoon black pepper, liquid smoke, whiskey, garlic powder, paprika, onion powder, dark molasses, and 1/2 tablespoon ground chile pepper. Bring mixture to a boil, then reduce heat. Simmer for 1 1/4 hours, uncovered, or until sauce thickens. Remove from heat, and set sauce aside",
      "Preheat an outdoor grill for high heat",
      "Remove the ribs from the oven, and let stand 10 minutes. Remove the racks from the foil, and place on the grill. Grill the ribs for 3 to 4 minutes on each side. Brush sauce on the ribs while they're grilling, just before you serve them (adding it too early will burn it).",
    ],
  },
];

export default BlogsData;
